Acme\ShagtvBundle\Entity\Comments:
    type: entity
    table: comments
    indexes:
        FK_comments_posts:
            columns:
                - post_id
        FK_5F9E962AA76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: string
            nullable: true
            length: 5000
            fixed: false
            comment: ''
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        post:
            targetEntity: Posts
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                post_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
