Acme\ShagtvBundle\Entity\Posts:
    type: entity
    table: posts
    indexes:
        FK_posts_posts:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: true
            comment: ''
            default: ''
        text:
            type: string
            nullable: true
            length: 5000
            fixed: false
            comment: ''
            default: ''
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        comments:
            targetEntity: Comments
            mappedBy: post
    lifecycleCallbacks: {  }
