acme_shagtv_posts:
    resource: "@AcmeShagtvBundle/Resources/config/routing/posts.yml"
    prefix:   /posts

acme_shagtv_comments:
    resource: "@AcmeShagtvBundle/Resources/config/routing/comments.yml"
    prefix:   /comments

acme_shagtv_users:
    resource: "@AcmeShagtvBundle/Resources/config/routing/users.yml"
    prefix:   /users

acme_shagtv_index:
    path:     /
    defaults: { _controller: AcmeShagtvBundle:Default:index, _format: html}

acme_shagtv_info:
    path:     /info/{id}
    defaults: { _controller: AcmeShagtvBundle:Default:info }

acme_shagtv_edit:
    path:     /edit/{id}
    defaults: { _controller: AcmeShagtvBundle:Default:edit }

acme_shagtv_new:
    path:     /new
    defaults: { _controller: AcmeShagtvBundle:Default:new }

acme_shagtv_remove:
    path:     /remove/{id}
    defaults: { _controller: AcmeShagtvBundle:Default:remove }

acme_shagtv_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeShagtvBundle:Default:hello }